### ISSUE TITLE
Not working with latest Cowin Site  update.

### ISSUE THREAD

**Issue by pra17dod** [hyper-trophy/VaccASSIST#2]
The extension is not working after the latest site update.
With this error message in console. 
>Uncaught (in promise) Error: Could not load file: 'mainscript.js'.

**Comment by hyper-trophy** [comment]
I guess you are on Linux, Please do a quick fix from below image, will update this soon
![Screenshot_20210516-182213](https://user-images.githubusercontent.com/74944866/118397876-b8a13900-b673-11eb-86e6-1619a199e0bc.png)

**Comment by pra17dod** [comment]
Ya, I too got to the same fix. Thanks and this is awesome. Keep it up!!
