### ISSUE TITLE
How long does session remain active?

### ISSUE THREAD

**Issue by chetan1989-cloud** [hyper-trophy/VaccASSIST#3]
Hi, I just wanted to know how long can the Cowin session remain active and list keeps getting refreshed by your extension?

What I saw was that after sometime it logs out and asks to enter OTP again. Is it expected? Because I have only 1 centre in my district and during re-login I might lose out on valuable time to book the slot.

**Comment by hyper-trophy** [comment]
Yes cowin website automatically logs you out after certain interval of time (almost half an hour), so you need to log in, even if you do it manually it will log out after some time, so that's not extension fault.

**Comment by chetan1989-cloud** [comment]
Thanks for clarifying, so I should I try to login and start the extension during the half hour interval in which slot usually opens.
