### ISSUE TITLE
getting error in console (error might be in queryselector)

### ISSUE THREAD

**Issue by krish-0003** [hyper-trophy/VaccASSIST#6]
![image](https://user-images.githubusercontent.com/71602041/119448926-92ecf180-bd4f-11eb-8190-ac1c92a853bd.png)
getting this error in console as well as in extension.
![image](https://user-images.githubusercontent.com/71602041/119449048-bf087280-bd4f-11eb-8e43-40d78dd14a3c.png)

**Comment by hyper-trophy** [comment]
I Will try to fix soon

**Comment by hyper-trophy** [comment]
I guess you are doing from home page of cowin website, please login -> schedule, and now try the extension
This will not work on home page search.

**Comment by krish-0003** [comment]
no brother I am doing after login and this is working perfectly but I am a developer so I check it in the console and see this error.
but thank you so much for providing this extension.thanks a lot.
