### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by akash-r-prabhu** [hyper-trophy/VaccASSIST#7]
anonymous function error showed in chrome extensions
in VaccAssist 4.5
/*
   Uncaught (in promise) ReferenceError: boxes is not defined
  mainscript.js:51 (anonymous function)
              console.log(boxes);
*/

**Comment by hyper-trophy** [comment]
Download latest one from here it's fixed https://www.udrop.com/5yjg/VaccAssistV4-5.zip

**Comment by akash-r-prabhu** [comment]
Thanks
