### ISSUE TITLE
Too many search requests, please try after sometime!

### ISSUE THREAD

**Issue by fohimuddin** [hyper-trophy/VaccASSIST#9]
I am getting this error and I know this is due to CoWin Site. I tired to increase the refresh rate to 15sec but there is this same issue. 

What I have figured that these errors are only available to CoWin Site, but if we access CoWin though Web Umang ( Not taking about the Android App) these errors are not there and neither do we need Captch. If you can Tweak your Extension to work with CoWin through Umang, it will be very much helpful.

I know I might sounding like an idiot and this is too much to ask for.

Anway thanks for what we have currently.
![Screenshot 2021-06-02 09 56 12](https://user-images.githubusercontent.com/85290485/120638059-490db500-c48d-11eb-997a-76b4c71db55c.png)

**Comment by hyper-trophy** [comment]
Yes ican tweak it to fit with umang app
Will do it asap

**Comment by fohimuddin** [comment]
Oh thats great... Plz do ping me at my mail id fohimuddin@gmail.com if any assistant/help required.
